---
title: "Mælaborð 3"
author: "Gígja Marín"
date: "2024-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Hlaða nauðsynlegum bókasöfnum
library(shiny)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DBI)
library(RSQLite)
library(stringr)
library(bslib)
library(plotly)

# Tengist SQLite gagnagrunninum og sækir gögn
conn <- dbConnect(SQLite(), "C:\\Users\\Ásdís\\OneDrive - Kvennaskolinn i Reykjavik\\Desktop\\Documents\\HÍ haust 24\\Upplýsingaverkfræði\\capstone-the-north\\data\\rotten_tomatoes.db")

dbDisconnect(conn)

# Fyrir lýsingu á leikurum
# Skilgreinir fall til að stytta texta eftir 6 setningar
shorten_biography <- function(bio) {
  sentences <- str_split(bio, "\\.")[[1]]
  shortened <- paste(sentences[1:min(6, length(sentences))], collapse = ". ")
  return(paste0(shortened, "."))
}

# Styttir lýsingar fyrir báða leikarana
actors_info$short_bio <- sapply(actors_info$mini_biography, shorten_biography)


# Búa til sérsniðið þema
my_theme <- bs_theme(
  bootswatch = "flatly",
  primary = "#4A90E2",
  secondary = "#50E3C2",
  base_font = font_google("Roboto")
)

# SHINY MÆLABORÐ

ui <- fluidPage(
  theme = my_theme,
  tags$head(
    tags$style(HTML("
      .header-title {
        text-align: center;
        font-size: 36px;
        font-weight: bold;
      }
      .header-subtitle {
        text-align: center;
        font-size: 24px;
        color: #666666;
      }
    "))
  ),
  
  # Aðal fyrirsögn
  div(class = "header-title", "Samanburður og yfirlit yfir kvikmyndir"),
  # Undirfyrirsögn
  div(class = "header-subtitle", "Rotten Tomatoes; Leonardo DiCaprio vs Kate Winslet"),
  
  tabsetPanel(
    tabPanel("Heim",
             h4("Um síðu"),
             br(),
             p("Þetta mælaborð veitir upplýsingar um leikarana Kate Winslet og Leonardo DiCaprio, ásamt yfirliti yfir kvikmyndir þeirra. Gögnin eru frá Rotten Tomatoes og hefur allar upplýsingar þaðan fram til 31.10.2020"),
             br(),
             fluidRow(
               column(6,
                      h4(actors_info$name[1]),
                      img(src = actors_info$headshot[1], height = "100px"),
                      p(actors_info$short_bio[1])
               ),
               column(6,
                      h4(actors_info$name[2]),
                      img(src = actors_info$headshot[2], height = "100px"),
                      p(actors_info$short_bio[2])
               )
             )),
    
tabPanel("Tegund",
      sidebarLayout(
        sidebarPanel(
          width = 3, 
          tags$p(
            "Upplýsingar",
            style = "font-size: 16px; "
          ),
          tags$p(
            "Gröfin sýna hversu margar myndir leikararnir hafa leikið í eftir tegund og hvaða einkunnir þær myndir eru að fá. Sumar myndir eru með fleiri en eina genre (t.d. drama og romance) og þá fara þær myndir í báða flokka",
            style = "font-size: 14px; line-height: 1.5;"
          )
        ),
        mainPanel(
          width = 9, 
          selectInput(
            "genre",
            "Veldu tegund (genre):",
            choices = NULL,
            selected = "Overall"
          ),
          br(),
          fluidRow(
            column(4, plotOutput("ratingPlot")),
            column(4, plotOutput("winsletRatingHist")),
            column(4, plotOutput("dicaprioRatingHist"))
          ),
          br()
        )
      )
    ),
    

tabPanel("Flokkun efnis",
      fluidRow(
        column(
          9, 
          plotOutput("content_rating_plot")
        ),
        column(
          3,
          # Grár bakgrunnur fyrir "Upplýsingar um graf"
          tags$div(
            style = "background-color: #f0f0f0; padding: 10px; border-radius: 5px;",
            tags$p("Upplýsingar", style = "font-size: 16px; "),
            tags$p("Þetta graf sýnir hversu margar myndir leikararnir hafa leikið í eftir flokkun efnis (content rating) og hve mörg prósent af myndunum þeirra það er.", style = "font-size: 14px; ")
          ),
          # Skýring á hvítum bakgrunn
          h4("Skýring"),
          p(HTML(
            "<b>G:</b> General Audience<br>
             <b>NR:</b> Not Rated<br>
             <b>PG:</b> Parental Guidance<br>
             <b>PG-13:</b> Parents Strongly Cautioned (13+)<br>
             <b>R:</b> Restricted (17+)"
          ))
        )
      )
    ),
    
    tabPanel("Einkunnir",
             sidebarLayout(
               sidebarPanel(width = 3, 
                            tags$p("Upplýsingar", style = "font-size: 16px;"),
                            tags$p("Gröfin sýna muninn á einkunn sem gagnrýnendur (tomatometer_rating) og áhorfendur (audience_rating) hafa gefið myndunum sem Winslet og Dicaprio hafa leikið í. Hægt er að fara yfir punktana og sjá nafn myndar. ", style = "font-size: 14px; line-height: 1.5;"),
                            tags$p("Gagnrýnendur: Löggiltir meðlimir ýmissa rithöfunda eða kvikmyndagagnrýnendasamtaka.", style = "font-size: 14px;"),
                            tags$p("Áhorfendur: Venjulegir notendur sem hafa gefið myndinni einkunn.", style = "font-size: 14px;"),
                            ),
               mainPanel(width = 9,
                         plotlyOutput("rating_trend_plot_dicaprio"),
                         br(),
                         br(),
                         plotlyOutput("rating_trend_plot_winslet"),
                         br(),
                         br(),
                         ),
             )),
    
tabPanel("Tímalengd",
        sidebarLayout(
          sidebarPanel(
            width = 3, 
            tags$p(
              "Upplýsingar",
              style = "font-size: 16px;"
            ),
            tags$p(
              "Þetta graf sýnir hvort lengd myndar hefur áhrif á einkunn hennar. Hægt er að fara yfir punktana og þar sést m.a. lýsing á myndinni frá Rotten Tomatoes. ",
              style = "font-size: 14px; line-height: 1.5;"
            )
          ),
          mainPanel(
            width = 9, 
            plotlyOutput("rating_runtime_plot")
          )
        )),
    
tabPanel("Tengslanet",
             h3("Tengslanet fyrir aðalleikara"),
             tags$iframe(src = "http://127.0.0.1:8063/", height = "600", width = "100%")
    )
  )
)

server <- function(input, output, session) {
  # Uppfæra tegundarvalkosti
  observe({
    genres <- unique(unlist(strsplit(as.character(rotten_tomatoes_leo_kate$genres), ",\\s*")))
    genres <- c("Overall", genres)
    updateSelectInput(session, "genre", choices = genres)
  })
  
  #CONTENT RATING
  output$content_rating_plot <- renderPlot({
    content_rating_count <- bind_rows(
      leo_movies_count %>% mutate(actor = "Leonardo DiCaprio"),
      kate_movies_count %>% mutate(actor = "Kate Winslet")
    )

  

    # Full útskýring fyrir skýringuna
    rating_labels_long <- c(
      "R" = "Restricted (17+)", 
      "G" = "General Audience", 
      "PG-13" = "Parents Strongly Cautioned (13+)", 
      "NR" = "Not Rated", 
      "PG" = "Parental Guidance"
    )
    
    ggplot(content_rating_count, aes(x = content_rating, y = count, fill = actor)) +
      geom_bar(stat = "identity", position = position_dodge(width = 0.7), color = "black") +
      geom_text(
        aes(label = paste0(round(percentage, 1), "%")),
        position = position_dodge(width = 0.7), vjust = -0.5, size = 4
      ) +
      scale_fill_manual(values = c("Leonardo DiCaprio" = "skyblue", "Kate Winslet" = "pink")) +
        labs(
        title = "Fjöldi mynda eftir flokkun efnis",
        x = "Flokkun efnis",
        y = "Fjöldi mynda",
        fill = "Actor"
      ) +
      ylim(0, max(content_rating_count$count) * 1.2) +
      theme_minimal() +
      theme(
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 10),
        legend.position = "right"
      ) +
      guides(fill = guide_legend(override.aes = list(color = NA), title = "Leikari"))  
  })
  
  # SAMANBURÐUR EFTIR GENRE
output$ratingPlot <- renderPlot({
    req(input$genre)
    
    if (input$genre == "Overall") {
      genre_data <- rotten_tomatoes_leo_kate %>%
        mutate(actor = case_when(
          grepl("Leonardo DiCaprio", actors) ~ "Leonardo DiCaprio",
          grepl("Kate Winslet", actors) ~ "Kate Winslet",
          TRUE ~ NA_character_
        )) %>%
        filter(!is.na(actor)) %>%
        group_by(actor) %>%
        summarize(movie_count = n_distinct(movie_title))
    } else {
      genre_data <- rotten_tomatoes_leo_kate %>%
        separate_rows(genres, sep = ",\\s*") %>%
        filter(genres == input$genre) %>%
        mutate(actor = case_when(
          grepl("Leonardo DiCaprio", actors) ~ "Leonardo DiCaprio",
          grepl("Kate Winslet", actors) ~ "Kate Winslet",
          TRUE ~ NA_character_
        )) %>%
        filter(!is.na(actor)) %>%
        group_by(actor) %>%
        summarize(movie_count = n_distinct(movie_title))
    }
    
    ggplot(genre_data, aes(x = actor, y = movie_count, fill = actor)) +
      geom_bar(stat = "identity") +
      geom_text(aes(label = paste0("Fjöldi: ", movie_count)), vjust = -0.3, size = 5) +
      ylim(0, max(genre_data$movie_count) * 1.2) +
      labs(title = paste("Fjöldi mynda:", input$genre), x = "Leikari", y = "Fjöldi mynda") +
      theme_minimal() +
      guides(fill = "none") + # Þetta fjarlægir skýringuna 
      scale_fill_manual(values = c("Kate Winslet" = "pink", "Leonardo DiCaprio" = "skyblue"))+
      theme(plot.title = element_text(face = "bold"))
  })
  
  # Histogram fyrir dreifingu áhorfendaeinkunna fyrir Kate Winslet
output$winsletRatingHist <- renderPlot({
    req(input$genre)
    
    if (input$genre == "Overall") {
      rating_data <- rotten_tomatoes_leo_kate %>%
        filter(grepl("Kate Winslet", actors), !is.na(audience_rating))
    } else {
      rating_data <- rotten_tomatoes_leo_kate %>%
        separate_rows(genres, sep = ",\\s*") %>%
        filter(genres == input$genre, grepl("Kate Winslet", actors), !is.na(audience_rating))
    }
    
    ggplot(rating_data, aes(x = audience_rating)) +
      geom_histogram(binwidth = 5, fill = "pink", color = "black", alpha = 0.7) +
      labs(title = paste("Kate Winslet: Dreifing einkunna"), x = "Áhorfendaeinkunn", y = "Fjöldi mynda") +
      xlim(0, 100) + ylim(0, 6) + theme_minimal() +
      theme(plot.title = element_text(face = "bold"))
})
  
  # Histogram fyrir dreifingu áhorfendaeinkunna fyrir Leonardo DiCaprio
  output$dicaprioRatingHist <- renderPlot({
    req(input$genre)
    
    if (input$genre == "Overall") {
      rating_data <- rotten_tomatoes_leo_kate %>%
        filter(grepl("Leonardo DiCaprio", actors), !is.na(audience_rating))
    } else {
      rating_data <- rotten_tomatoes_leo_kate %>%
        separate_rows(genres, sep = ",\\s*") %>%
        filter(genres == input$genre, grepl("Leonardo DiCaprio", actors), !is.na(audience_rating))
    }
    
    ggplot(rating_data, aes(x = audience_rating)) +
      geom_histogram(binwidth = 5, fill = "skyblue", color = "black", alpha = 0.7) +
      labs(title = paste("Leonardo DiCaprio: Dreifing einkunna"), x = "Áhorfendaeinkunn", y = "Fjöldi mynda") +
      xlim(0, 100) + ylim(0,6) + theme_minimal()+
      theme(plot.title = element_text(face = "bold"))
  })
  
 
  
  #EINKUNNIR GAGNRÝNENDA VS ÁHORFENDA
  
  # Gögn fyrir Leonardo DiCaprio
  trend_data_dicaprio <- reactive({
    leo_movies %>%
      mutate(
        original_release_date = as.Date(original_release_date),
        critics_label = paste("Mynd:", movie_title, "<br>Einkunn gagnrýnenda:", tomatometer_rating, "<br>Útgáfudagur:", original_release_date),
        audience_label = paste("Mynd:", movie_title, "<br>Einkunn áhorfenda:", audience_rating, "<br>Útgáfudagur:", original_release_date)
      ) %>%
      filter(!is.na(original_release_date))
  })
  
  # Gögn fyrir Kate Winslet
  trend_data_winslet <- reactive({
    kate_movies %>%
      mutate(
        original_release_date = as.Date(original_release_date),
        critics_label = paste("Mynd:", movie_title, "<br>Einkunn gagnrýnenda:", tomatometer_rating, "<br>Útgáfudagur:", original_release_date),
        audience_label = paste("Mynd:", movie_title, "<br>Einkunn áhorfenda:", audience_rating, "<br>Útgáfudagur:", original_release_date)
      ) %>%
      filter(!is.na(original_release_date))
  })
  
  # Graf fyrir Leonardo DiCaprio
  output$rating_trend_plot_dicaprio <- renderPlotly({
    trend_comparison_plot_dicaprio <- ggplot(trend_data_dicaprio(), aes(x = original_release_date)) +
      # Lóðréttar línur á milli gagnrýnenda- og áhorfendaeinkunna
      geom_segment(aes(x = original_release_date, xend = original_release_date,
                       y = tomatometer_rating, yend = audience_rating),
                   color = "grey", size = 0.5, alpha = 0.5) +
      # Punktar fyrir gagnrýnenda- og áhorfendaeinkunnir
      geom_point(aes(y = tomatometer_rating, color = "Gagnrýnendur ", text = critics_label), size = 2, alpha = 0.7) +
      geom_point(aes(y = audience_rating, color = "Áhorfendur ", text = audience_label), size = 2, alpha = 0.7) +
      # Trendlínur fyrir gagnrýnenda- og áhorfendaeinkunnir
      geom_smooth(aes(y = tomatometer_rating, color = "Gagnrýnendur ", linetype = "Trendline"), 
                  method = "lm", size = 0.5, se = FALSE) +
      geom_smooth(aes(y = audience_rating, color = "Áhorfendur ", linetype = "Trendline"), 
                  method = "lm", size = 0.5, se = FALSE) +
      # Stillir táknskýringu fyrir liti og línutegundir
      scale_color_manual(values = c("Gagnrýnendur " = "magenta", "Áhorfendur " = "seagreen1")) +
      scale_linetype_manual(values = c("Trendline" = "dashed")) +
      labs(title = "Leonardo DiCaprio: Einkunnir gagnrýnenda vs áhorfenda",
           x = "Útgáfudagur",
           y = "Einkunn",
           color = "") +
      theme_minimal(base_size = 10) +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"))
    
    ggplotly(trend_comparison_plot_dicaprio, tooltip = "text")
  })
  
  # Graf fyrir Kate Winslet
  output$rating_trend_plot_winslet <- renderPlotly({
    trend_comparison_plot_winslet <- ggplot(trend_data_winslet(), aes(x = original_release_date)) +
      # Lóðréttar línur á milli gagnrýnenda- og áhorfendaeinkunna
      geom_segment(aes(x = original_release_date, xend = original_release_date,
                       y = tomatometer_rating, yend = audience_rating),
                   color = "grey", size = 0.5, alpha = 0.5) +
      # Punktar fyrir gagnrýnenda- og áhorfendaeinkunnir
      geom_point(aes(y = tomatometer_rating, color = "Gagnrýnendur ", text = critics_label), size = 2, alpha = 0.7) +
      geom_point(aes(y = audience_rating, color = "Áhorfendur ", text = audience_label), size = 2, alpha = 0.7) +
      # Trendlínur fyrir gagnrýnenda- og áhorfendaeinkunnir
      geom_smooth(aes(y = tomatometer_rating, color = "Gagnrýnendur ", linetype = "Trendline"), 
                  method = "lm", size = 0.5, se = FALSE) +
      geom_smooth(aes(y = audience_rating, color = "Áhorfendur ", linetype = "Trendline"), 
                  method = "lm", size = 0.5, se = FALSE) +
      # Stillir táknskýringu fyrir liti og línutegundir
      scale_color_manual(values = c("Gagnrýnendur " = "magenta", "Áhorfendur " = "seagreen1")) +
      scale_linetype_manual(values = c("Trendline" = "dashed")) +
      labs(title = "Kate Winslet: Einkunnir gagnrýnenda vs áhorfenda",
           x = "Útgáfudagur",
           y = "Einkunn",
           color = "") +
      theme_minimal(base_size = 10) +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"))
    
    ggplotly(trend_comparison_plot_winslet, tooltip = "text")
  })
  
  #RUNTIME
  # Audience Rating vs Runtime plot
output$rating_runtime_plot <- renderPlotly({
    plot_data <- rotten_tomatoes_leo_kate %>%
      mutate(
        both_actors = grepl("Leonardo DiCaprio", actors) & grepl("Kate Winslet", actors),
        actor = case_when(
          both_actors ~ "Both",
          grepl("Leonardo DiCaprio", actors) ~ "Leonardo DiCaprio",
          grepl("Kate Winslet", actors) ~ "Kate Winslet",
          TRUE ~ NA_character_
        )
      ) %>%
      filter(!is.na(actor))
    
    # Notum <br> fyrir línuskipti og stytta texta ef þarf
    plot_data <- plot_data %>%
      mutate(
        hover_text = paste(
          "<b>Title:</b>", movie_title,
          "<br><b>Lengd:</b>", runtime, " mín", 
          "<br><b>Áhorfendaeinkunn:</b>", audience_rating,
          "<br><br><b>Info:</b>", str_wrap(movie_info, width = 50) %>% str_replace_all("\n", "<br>")
        )
      )
    
    p <- ggplot(plot_data, aes(x = audience_rating, y = runtime, color = actor, shape = actor)) +
      geom_point(aes(text = hover_text), size = 2) +  # Minnka punktana í size = 2
      scale_color_manual(values = c("Leonardo DiCaprio" = "skyblue", 
                                    "Kate Winslet" = "pink", 
                                    "Both" = "gold")) +
      scale_shape_manual(values = c("Leonardo DiCaprio" = 16, "Kate Winslet" = 16, "Both" = 8)) +
      labs(title = "Áhrif lengdar á mynd",
           x = "Áhorfendaeinkunn",
           y = "Lengd myndar í mínútum",
           color = "Leikari",
           shape = "Leikari") +
    theme_minimal(base_size = 10) +
      theme(plot.title = element_text(hjust = 0.5, face = "bold"))
    
    # Breytum ggplot í plotly og stillum tooltip
    ggplotly(p, tooltip = "text") %>%
      layout(hoverlabel = list(align = "left"))  # Stilla hover textann til vinstri
})
}

# Keyra Shiny appið
shinyApp(ui = ui, server = server)
```

